import type { Metadata } from 'next'
import './globals.css'
import UILibraryProvider from '@/providers/UILibraryProvider'


export const metadata: Metadata = {
  title: 'SheyEvents',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <UILibraryProvider>
            {children}
        </UILibraryProvider>
      </body>
    </html>
  )
}
